### ISSUE TITLE
TomEE and live reload produces unsightly exception

### ISSUE THREAD

**Issue by joheriks** [vaadin/skeleton-starter-flow-cdi#137]
When live reload is enabled, a SEVERE level error is logged:
```
16-Dec-2019 14:17:45.333 SEVERE [http-nio-8080-exec-1] org.apache.catalina.session.StandardManager.startInternal Exception loading sessions from persistent storage
	java.io.StreamCorruptedException: invalid type code: 00
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1601)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:561)
		at java.lang.Throwable.readObject(Throwable.java:914)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
		at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1589)
		at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1077)
		at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:217)
		at org.apache.catalina.session.StandardManager.load(StandardManager.java:161)
		at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:351)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5253)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3828)
		at org.apache.tomee.catalina.deployment.TomcatWebappDeployer.reload(TomcatWebappDeployer.java:95)
		at org.apache.openejb.assembler.DeployerEjb.reload(DeployerEjb.java:476)
		at org.apache.openejb.assembler.DeployerEjb.reload(DeployerEjb.java:464)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
		at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
		at org.apache.openejb.security.internal.InternalSecurityInterceptor.invoke(InternalSecurityInterceptor.java:35)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
		at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
		at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:191)
		at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:102)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
		at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
		at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
		at org.apache.openejb.core.singleton.SingletonContainer._invoke(SingletonContainer.java:272)
		at org.apache.openejb.core.singleton.SingletonContainer.invoke(SingletonContainer.java:221)
		at org.apache.openejb.server.ejbd.EjbRequestHandler.doEjbObject_BUSINESS_METHOD(EjbRequestHandler.java:371)
		at org.apache.openejb.server.ejbd.EjbRequestHandler.processRequest(EjbRequestHandler.java:182)
		at org.apache.openejb.server.ejbd.EjbDaemon.processEjbRequest(EjbDaemon.java:360)
		at org.apache.openejb.server.ejbd.EjbDaemon.service(EjbDaemon.java:247)
		at org.apache.openejb.server.ejbd.EjbServer.service(EjbServer.java:104)
		at org.apache.openejb.server.httpd.ServerServlet.service(ServerServlet.java:60)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
```

This should be prevented / elided.

Java: `jdk1.8.0_202`
Vaadin:  `14.1.2`

**Comment by joheriks** [comment]
*Observation.* the above exception is thrown on reload when the `Button` with the lambda containing the bean reference is created in the view constructor:
```java
class MainView {

    public MainView() {
        Button button = new Button("Click me",
                event -> Notification.show(messageBean.getMessage()));
        add(button);
    }
}
```

However, if the Button creation is deferred to a `@PostConstruct` method, the exception is no longer thrown on reload:
```java
class MainView {
   
    @PostConstruct
    public init() {
        Button button = new Button("Click me",
                event -> Notification.show(messageBean.getMessage()));
        add(button);
    }
}
```
