### ISSUE TITLE
[node 17] current v23 branch is not working

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/skeleton-starter-flow-cdi#406]
the current version is 23.0.4
running `mvn wildfly:run` failed (but working in production mode)

```
11:34:25,002 INFO  [stdout] (dev-server-output) ------------------ Frontend compilation failed. ------------------
11:34:25,002 INFO  [stdout] (dev-server-output)
11:34:27,027 WARN  [com.vaadin.base.devserver.AbstractDevServerRunner] (ForkJoinPool.commonPool-worker-19) Webpack port '62712' is defined but it's not working properly. Using a new free port...
11:34:27,027 INFO  [com.vaadin.base.devserver.AbstractDevServerRunner] (ForkJoinPool.commonPool-worker-19) Starting Webpack
11:34:30,919 INFO  [stdout] (ForkJoinPool.commonPool-worker-19)

```

after open the view

```
javax.servlet.ServletException: com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: Startup of Webpack failed. Output was:
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:52847/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.106:52847/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1c4f:5e5e:c164:e992]:52847/
<i> [webpack-dev-server] Content not from webpack is served from 'C:\Users\Tarek Oraby\Downloads\skeleton-starter-flow-cdi-23\skeleton-starter-flow-cdi-23\target\classes\META-INF\VAADIN\webapp, C:\Users\Tarek Oraby\Downloads\skeleton-starter-flow-cdi-23\skeleton-starter-flow-cdi-23\src\main\webapp' directory
Watchdog connection error. Terminating webpack process...

	at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:301)
	at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.cdi.CdiVaadinServlet.service(CdiVaadinServlet.java:67)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.2.14.Final//io.un
....
```

Maven : apache-maven-3.8.4
Java version: 11.0.13, 
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
node 17.4.0
npm 8.3.1

![image](https://user-images.githubusercontent.com/31067185/162398309-2b2b3777-5989-40c2-b2e2-7a7ea06a8cf7.png)

**Comment by ZheSun88** [comment]
adding ` <requireHomeNodeExec>true</requireHomeNodeExec>` to the vaadin maven plugin fix the issue.

**Comment by ZheSun88** [comment]
found one related ticket https://github.com/nodejs/node/issues/40537

And here is a workaround with the wildfly maven plugin
```
mvn wildfly:run -Dwildfly.javaOpts="-Xms64m -Xmx512m -Djava.net.preferIPv4Stack=false -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman"
```
**-Djava.net.preferIPv4Stack=false does the trick**

**Comment by mcollovati** [comment]
Just to add some context it seems that the problem happens because `WatchDogServer` binds to 0.0.0.0 (potentially because by default wildfly maven plugin sets `-Djava.net.preferIPv4Stack=true` system property), but when `runWatchDog` function defined in `webpack.generated.js` connects to localhost, it resolves it as `::1`, and thus client receives a `connect ECONNREFUSED` and kills webpack process.

**Comment by ZheSun88** [comment]
Tested with Vaadin 23.0.9. 
this issue has been fixed already by https://github.com/vaadin/flow/pull/13506
