### ISSUE TITLE
FileWatcher exception with Vaadin 24.4

### ISSUE THREAD

**Issue by mshabarov** [vaadin/skeleton-starter-flow-cdi#636]
The following exception is thrown when I start the app with Vaadin 24.4.0.alpha11:
```
15:13:19,712 ERROR [com.vaadin.base.devserver.FileWatcher] (ForkJoinPool.commonPool-worker-1) Error starting file watcher: java.lang.NoClassDefFoundError: com/sun/nio/file/ExtendedWatchEventModifier
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:454)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:433)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//io.methvin.watcher.DirectoryWatcher.registerPaths(DirectoryWatcher.java:282)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//io.methvin.watcher.DirectoryWatcher.watchAsync(DirectoryWatcher.java:229)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//io.methvin.watcher.DirectoryWatcher.watchAsync(DirectoryWatcher.java:215)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.base.devserver.FileWatcher.start(FileWatcher.java:65)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.base.devserver.ThemeLiveUpdater.<init>(ThemeLiveUpdater.java:77)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.base.devserver.DevModeHandlerManagerImpl.startWatchingThemeFolder(DevModeHandlerManagerImpl.java:145)
        at deployment.project-base-flow-cdi-1.0-SNAPSHOT.war//com.vaadin.base.devserver.DevModeHandlerManagerImpl.lambda$initDevModeHandler$0(DevModeHandlerManagerImpl.java:108)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ClassNotFoundException: com.sun.nio.file.ExtendedWatchEventModifier from [Module "deployment.project-base-flow-cdi-1.0-SNAPSHOT.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 16 more

```

This however doesn't affect application functionality.

**Comment by mcollovati** [comment]
Related to https://github.com/vaadin/flow/issues/17159

**Comment by mcollovati** [comment]
The reason of the error is that with Widlfly "Not all JDK classes are exposed to a deployment by default"

https://docs.wildfly.org/31/Developer_Guide.html#accessing-jdk-classes

It can be fixed by placing a file named `jboss-deployment-structure.xml` with the following content in `src/main/webapp/WEB-INF`

```xml
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <deployment>
        <dependencies>
            <system export="true">
                <paths>
                    <path name="com/sun/nio/file"/>
                </paths>
            </system>
        </dependencies>
    </deployment>
</jboss-deployment-structure>

```

**Comment by mcollovati** [comment]
Or as suggested by Artur here https://github.com/vaadin/flow/issues/17159#issuecomment-1617703993
