### ISSUE TITLE
vaadin.com/start/ page has wrong starting instructions

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/skeleton-starter-flow-cdi#78]
vaadin.com/start/ for the "Create an empty project" => JavaEE has instructions
 
Run the Maven `goal jetty:run`

This leads to 
> [ERROR] No plugin found for prefix 'jetty' in the current project

Project readme has instructions:
 `mvn clean package tomee:run`

but this leads to exceptions and server not starting correctly (empty page in localhost:8080):

> 03-Jul-2019 09:42:44.729 SEVERE [localhost-startStop-1] jdk.internal.reflect.NativeMethodAccessorImpl.invoke ContainerBase.removeChild: destroy:
>  org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_destroy]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]] in state [STARTING_PREP]
>         at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:402)
>         at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:292)
>         at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:854)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.undeploy(TomcatWebAppBuilder.java:1628)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.undeploy(TomcatWebAppBuilder.java:1608)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.undeployWebApps(TomcatWebAppBuilder.java:764)
>         at org.apache.openejb.assembler.classic.Assembler.destroyApplication(Assembler.java:2328)
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:1046)
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:721)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1299)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1125)
>         at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
>         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
>         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
>         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
>         at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
>         at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:835)
> 
> 03-Jul-2019 09:42:44.792 SEVERE [localhost-startStop-1] org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal Unable to deploy collapsed ear in war StandardEngine[Catalina].StandardHost[localhost].StandardContext[]
>  org.apache.openejb.OpenEJBException: Creating application failed: C:\Users\Juho\eclipse-workspace\vaadin_com_start_javaee_validation\target\apache-tomee\webapps\ROOT: Cannot get Unsafe.defineClass
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:1050)
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:721)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1299)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1125)
>         at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
>         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
>         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
>         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
>         at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
>         at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:835)
> Caused by: java.lang.IllegalStateException: Cannot get Unsafe.defineClass
>         at org.apache.webbeans.proxy.AbstractProxyFactory$4.run(AbstractProxyFactory.java:783)
>         at org.apache.webbeans.proxy.AbstractProxyFactory$4.run(AbstractProxyFactory.java:772)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
>         at org.apache.webbeans.proxy.AbstractProxyFactory.initializeUnsafe(AbstractProxyFactory.java:771)
>         at org.apache.webbeans.proxy.AbstractProxyFactory.<init>(AbstractProxyFactory.java:86)
>         at org.apache.webbeans.proxy.InterceptorDecoratorProxyFactory.<init>(InterceptorDecoratorProxyFactory.java:77)
>         at org.apache.webbeans.config.WebBeansContext.<init>(WebBeansContext.java:153)
>         at org.apache.webbeans.config.WebBeansContext.<init>(WebBeansContext.java:116)
>         at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:167)
>         at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:41)
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:917)
>         ... 17 more
> Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
>         at java.base/java.lang.Class.getDeclaredMethod(Class.java:2481)
>         at org.apache.webbeans.proxy.AbstractProxyFactory$4.run(AbstractProxyFactory.java:778)
>         ... 27 more
> 
> 03-Jul-2019 09:42:44.793 SEVERE [localhost-startStop-1] jdk.internal.reflect.NativeMethodAccessorImpl.invoke ContainerBase.addChild: start:
>  org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
>         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
>         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
>         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
>         at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
>         at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:835)
> Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.OpenEJBException: Creating application failed: C:\Users\Juho\eclipse-workspace\vaadin_com_start_javaee_validation\target\apache-tomee\webapps\ROOT: Cannot get Unsafe.defineClass
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1311)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1125)
>         at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
>         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>         ... 10 more
> Caused by: org.apache.openejb.OpenEJBException: Creating application failed: C:\Users\Juho\eclipse-workspace\vaadin_com_start_javaee_validation\target\apache-tomee\webapps\ROOT: Cannot get Unsafe.defineClass
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:1050)
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:721)
>         at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1299)
>         ... 15 more
> Caused by: java.lang.IllegalStateException: Cannot get Unsafe.defineClass
>         at org.apache.webbeans.proxy.AbstractProxyFactory$4.run(AbstractProxyFactory.java:783)
>         at org.apache.webbeans.proxy.AbstractProxyFactory$4.run(AbstractProxyFactory.java:772)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
>         at org.apache.webbeans.proxy.AbstractProxyFactory.initializeUnsafe(AbstractProxyFactory.java:771)
>         at org.apache.webbeans.proxy.AbstractProxyFactory.<init>(AbstractProxyFactory.java:86)
>         at org.apache.webbeans.proxy.InterceptorDecoratorProxyFactory.<init>(InterceptorDecoratorProxyFactory.java:77)
>         at org.apache.webbeans.config.WebBeansContext.<init>(WebBeansContext.java:153)
>         at org.apache.webbeans.config.WebBeansContext.<init>(WebBeansContext.java:116)
>         at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:167)
>         at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:41)
>         at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:917)
>         ... 17 more
> Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
>         at java.base/java.lang.Class.getDeclaredMethod(Class.java:2481)
>         at org.apache.webbeans.proxy.AbstractProxyFactory$4.run(AbstractProxyFactory.java:778)
>         ... 27 more
> 
> 03-Jul-2019 09:42:44.793 SEVERE [localhost-startStop-1] jdk.internal.reflect.NativeMethodAccessorImpl.invoke Error deploying web application archive [C:\Users\Juho\eclipse-workspace\vaadin_com_start_javaee_validation\target\apache-tomee\webapps\ROOT.war]
>  java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
>         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
>         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
>         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
>         at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
>         at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:835)
> 
> 03-Jul-2019 09:42:44.795 INFO [localhost-startStop-1] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Deployment of web application archive [C:\Users\Juho\eclipse-workspace\vaadin_com_start_javaee_validation\target\apache-tomee\webapps\ROOT.war] has finished in [11,356] ms
> 03-Jul-2019 09:42:44.811 INFO [Catalina-startStop-1] org.apache.catalina.core.StandardContext.setClassLoaderProperty Unable to set the web application class loader property [clearReferencesRmiTargets] to [true] as the property does not exist.
> 03-Jul-2019 09:42:45.037 WARNING [Catalina-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [213] milliseconds.
> 03-Jul-2019 09:42:45.043 INFO [main] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Starting ProtocolHandler ["http-nio-8080"]
> 03-Jul-2019 09:42:45.050 INFO [main] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Starting ProtocolHandler ["ajp-nio-8009"]
> 03-Jul-2019 09:42:45.060 INFO [main] jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke Server startup in 11700 ms

**Comment by juhopiirainen** [comment]
This occurs with Java 12.
